version: '3.5'
services:
  # mysql-standalone:
  #   image: meusql-db
  #   ports:
  #     - "3307:3036"
  #   environment:
  #     MYSQL_ROOT_USER: root
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: fiap
  #     MYSQL_USER: MainUser
  #     MYSQL_PASSWORD: MainPassword
  backend:
    image: carteira-crypto
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/carteira-cryptos?serverTimezone=UTC&autoReconect=true&useSSL=false
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_DATASOURCE_PLATAFORM: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_DATASOURCE_INITIALIZATION-MODE: always
    build: 
      context: "./"
      dockerfile: "Dockerfile"
#     depends_on:
#       - mysql-standalone
# volumes:
#   db-volume:
