version: '3.5'
services:
  carteira-cryptos:
    container_name: CarteiraCryptos
    image: carteira-crypto
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:~/fiap/carteira-cryptos;DB_CLOSE_ON_EXIT=FALSE?serverTimezone=UTC&autoReconect=true&useSSL=false
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_DATASOURCE_PLATAFORM: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_DATASOURCE_INITIALIZATION-MODE: always
    build: 
      context: "./"
      dockerfile: "Dockerfile"
#     depends_on:
#       - mysql-standalone
# volumes:
#   db-volume:
