version: '3.5'
services:
  carteira-cryptos:
    container_name: mysqlCartCrypt
    image: meusql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    build: 
      context: "./"
      dockerfile: "Dockerfile"
      args:
        - DB2_USER=root
        - DB2_PASSWORD=root